status/urls.py
from django.urls import path, include
from .views import status, load_balancer

app_name="status"

urlpatterns = [
    path('', status, name="status"),
    path('load', load_balancer, name="load")
]

story6/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('status.urls')),
    path('story7/', include('story7.urls')),
    path('story8/', include('story8.urls')),
    path('story9/', include('story9.urls')),
    
]

story7/urls.py
from django.urls import path, include
from .views import profile

app_name="story7"

urlpatterns = [
    path('', profile, name="profile"),
]

story8/urls.py
from django.urls import path, include
from .views import story8

app_name="story8"

urlpatterns = [
    path('', story8, name="story8"),
]

story9/urls.py
from django.urls import path, include
from .views import *

app_name="story9"

urlpatterns = [
    path('', story9, name="story9"),
    path('login/', login1, name="login"),
    path('logout/', logout1, name="logout")
]

status/models.py
from django.db import models
# from django.utils import timezone
# import datetime
# Create your models here.
class Status(models.Model):
    status = models.CharField(max_length=500)
    time = models.DateTimeField(blank=True, null=True)

    def __str__(self):
        return self.status

story7/models.py
from django.db import models

# Create your models here.

story8/models.py
from django.db import models

# Create your models here.

story9/models.py
from django.db import models

# Create your models here.

status/forms.py
from django import forms
from .models import Status

class StatusForm(forms.ModelForm):
    class Meta:
        model = Status
        fields = ["status"]
    
    def __init__(self, *args, **kwargs):
        super(StatusForm, self).__init__(*args, **kwargs)

        self.fields["status"].widget.attrs['class'] = "input-status"
        self.fields["status"].widget.attrs['id'] = "input-status"

status/views.py
from django.shortcuts import render, redirect
from .forms import StatusForm
from .models import Status
import datetime
# Create your views here.
def status(request):
    if request.method == "POST":
        form = StatusForm(request.POST)
        if form.is_valid():
            status = form.save(commit=False)
            status.time = datetime.datetime.now()
            status.save()
            return redirect('status:status')
    else:
        form = StatusForm()
    status_objects = Status.objects.all().order_by("time").reverse()
    return render(request, 'status.html', {"form": form, "status_objects": status_objects})

def load_balancer(request):
    return render(request, 'loadbalancer.html')

story7/views.py
from django.shortcuts import render

# Create your views here.
def profile(request):
    return render(request, 'profile.html')

story8/views.py
from django.shortcuts import render

# Create your views here.
def story8(request):
    return render(request, "story8.html")

story9/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, logout
from django.contrib.auth.decorators import login_required

# Create your views here.
def story9(request):
    return render(request, "home.html")

def login1(request):
    if request.method == "POST":
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return redirect('/story9')
    else:
        form = AuthenticationForm()
    return render(request, 'login.html', {'form': form})

def logout1(request):
    logout(request)
    return redirect('/story9/login')

status/templates/loadbalancer.html
<!DOCTYPE html>
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.4.1.js" integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU=" crossorigin="anonymous"></script>
    <title>My First Load Balancer</title>
</head>
<body>
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-6 text-center offset-md-3 mt-5">
                <h1>My First Load Balancer</h1>
                <p>
                    In this page, I'll tell you about my experience on setting up my load balancer using Nginx and how to set it up.
                </p>
                <h3>What is a Load Balancer?</h3>
                <p>
                    A load balancer acts as the “traffic cop” sitting in front of your servers and routing client requests across all servers capable of fulfilling those requests in a manner that maximizes speed and capacity utilization and ensures that no one server is overworked, which could degrade performance. 
                    If a single server goes down, the load balancer redirects traffic to the remaining online servers. When a new server is added to the server group, the load balancer automatically starts to send requests to it.
                </p>
                <h3>How to Setup a Load Balancer Using Nginx</h3>
                <h4 class="mt-3">Download Nginx <a href="http://nginx.org/en/download.html">here</a></h4>
                <p class="mt-5">The next step is to open nginx.conf and type the code below</p>
                <img src="{% static 'pic/1.png' %}">
                <p class="mt-5">next, go ahead and open the command line where you store nginx</p>
                <img src="{% static 'pic/2.png' %}">
                <p class="mt-5">Open two separate command line and start 2 servers at once using the port 8000 and 9000</p>
            </div>
            <div class="col-md-12 text-center">
                <img src="{% static 'pic/3.png' %}">
            </div>
            <div class="col-md-6 text-center offset-md-3">
                <p class="mt-5">Refresh the page a few times and you'll see that both port are recieving request</p>
            </div>
            <div class="col-md-12 text-center">
                <img src="{% static 'pic/4.png' %}">
            </div>
            <div class="col-md-6 text-center offset-md-3">
                <p class="mt-5">If you shutdown one of the serves, there will be no problem on accessing it since the load balancer will just redirect it to the available one</p>
            </div>
                
                
               
                
                
            </div>
            <div class="row">
                <div class="col-md-12">

                </div>
            </div>
        </div>
    </div>
</body>

status/templates/status.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Status</title>
</head>
<body>
    <h2 class="halo">Halo, apa kabar?</h2>
    <form action="" method="POST">
        {% csrf_token %}
        {{ form }}
        <input type="submit" id="submit" value="post">
    </form>

    {% if status_objects %}
        {% for status in status_objects %}
            <div class="status">
                <h3 class="text">
                    {{ status.status }}
                </h3>
                <p class="time">{{ status.time|date:'d M Y | H:i' }}</p>
            </div>
        {% endfor %}
    {% endif %}
    
</body>
</html>

story7/templates/profile.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <link rel="stylesheet" type="text/css" href="{% static 'css/css.css' %}"/>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
        <link rel="stylesheet" href="https://code.jquery.com/ui/1.10.4/themes/smoothness/jquery-  ui.css">
        <!-- <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script> -->
        <script src="https://code.jquery.com/ui/1.10.4/jquery-ui.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
        <script src="{% static 'js.js' %}"></script>
        <title>Profile</title>
    </head>
    <body id="body">
        <div class="container-fluid">
            <div class="col-md-12 text-center mt-5">
                <h2 id="halo">Fadhil Pradipta</h2>
            </div>
            <div class="col-md-12 text-center mt-5">
                <label class="switch">
                    <input type="checkbox" id="switch" onclick="a()">
                    <span class="slider round"></span>
                </label>
            </div>
            <div id="accordion" class="col-md-6 offset-md-3 text-center mt-5">
                <h3>Aktivitas</h3>
                <div class="child">
                    <p>Piano is my lyfe</p>
                </div>
                <h3>Pengalaman Organisasi</h3>
                <div class="child">
                    <p>Ristek SIG Game Development</p>
                </div>
                <h3>Prestasi</h3>
                <div class="child">
                    <p>-</p>
                </div>
            </div>
        </div>
        
    </body>
</html>

story8/templates/story8.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'css/story8.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.4.1.js" integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU=" crossorigin="anonymous"></script>
    <script src="{% static 'story8.js' %}"></script>
    <title>Fadhil Buku</title>
</head>
<body>
    <div class="container-fluid">
        <div class="text-center mt-5">
            <h1>Search for books here!</h1>
        </div>
        <div class="row">
            <div class="col-md-2 offset-md-5">
                <input type="text" id="search" placeholder="Books">
            </div>
            <div class="col-md-2 mb-5">
                <input type="submit" id="button" value="Search">
            </div>
        </div>
        <div class="row">
            <table id="results" class="col-md-9 text-center offset-md-1">
            </table>
        </div>
    </div>
</body>
</html>

story9/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Home</title>
</head>
<body>

    {% if user.is_authenticated %}
    <h1>Hello, {{ user }}</h1>
    <a href="{% url 'story9:logout' %}">
        <button id="logout">Logout</button>
    </a>
    {% else %}
    <h1>Please login!</h1>
    <a href="{% url 'story9:login' %}">
        <button id="login">Login</button>
    </a>
    {% endif %}

</body>
</html>

story9/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>SLogin</title>
</head>
<body>
    <form class="auth-form" action="{% url 'story9:login' %}" method="POST">
        {% csrf_token %}
        <label for="id_username">Username:</label>
        <input type="text" name="username" autofocus="" required="" id="id_username">
        <label for="id_password">Password:</label>
        <input type="password" name="password" required="" id="id_password">
        {% if request.GET.next %}
            <input type="hidden" name="next" value="{{ request.GET.next }}">
        {% endif %}
        <input type="submit" id="login" value="Login">
    </form>
</body>
</html>